### ISSUE TITLE
Edit should fetch a single record FAILED

### ISSUE THREAD

**Issue by gh0st** [mraible/ng2-demo#10]
After running ng test the first 3 tests execute successfully but the last few all give the same `Cannot read property 'andReturn' of undefined`

```Chrome 54.0.2840 (Mac OS X 10.12.1) Component: Edit should fetch a single record FAILED
	TypeError: Cannot read property 'andReturn' of undefined
	    at new MockSearchService (webpack:///Users/chad/Developer/ng2demo/src/app/shared/search/mocks/search.service.ts:9:1425 <- src/test.ts:34062:1459)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/src/app/edit/edit.component.spec.ts:16:24 <- src/test.ts:43748:29)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:232:0 <- src/test.ts:59455:26)
	    at ProxyZoneSpec.onInvoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/proxy.js:79:0 <- src/test.ts:34825:39)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:231:0 <- src/test.ts:59454:32)
	    at Zone.run (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:114:0 <- src/test.ts:59337:43)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:34540:34)
	Error: Cannot create the component EditComponent as it was not imported into the testing module!
	    at TestBed.createComponent (webpack:///Users/chad/Developer/ng2demo/~/@angular/core/bundles/core-testing.umd.js:887:0 <- src/test.ts:6891:23)
	    at Function.TestBed.createComponent (webpack:///Users/chad/Developer/ng2demo/~/@angular/core/bundles/core-testing.umd.js:714:0 <- src/test.ts:6718:33)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/src/app/edit/edit.component.spec.ts:32:28 <- src/test.ts:43762:41)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:232:0 <- src/test.ts:59455:26)
	    at ProxyZoneSpec.onInvoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/proxy.js:79:0 <- src/test.ts:34825:39)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:231:0 <- src/test.ts:59454:32)
	    at Zone.run (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:114:0 <- src/test.ts:59337:43)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:34540:34)
Chrome 54.0.2840 (Mac OS X 10.12.1): Executed 4 of 9 (1 FAILED) (0 secs / 0.289 secs)
Chrome 54.0.2840 (Mac OS X 10.12.1) Component: Edit should fetch a single record FAILED
	TypeError: Cannot read property 'andReturn' of undefined
	    at new MockSearchService (webpack:///Users/chad/Developer/ng2demo/src/app/shared/search/mocks/search.service.ts:9:1425 <- src/test.ts:34062:1459)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/src/app/edit/edit.component.spec.ts:16:24 <- src/test.ts:43748:29)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:232:0 <- src/test.ts:59455:26)
	    at ProxyZoneSpec.onInvoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/proxy.js:79:0 <- src/test.ts:34825:39)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:231:0 <- src/test.ts:59454:32)
	    at Zone.run (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:114:0 <- src/test.ts:59337:43)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/jasmine-patch.js:102:0 <- src/test.ts:34540:34)
	Error: Cannot create the component EditComponent as it was not imported into the testing module!
	    at TestBed.createComponent (webpack:///Users/chad/Developer/ng2demo/~/@angular/core/bundles/core-testing.umd.js:887:0 <- src/test.ts:6891:23)
	    at Function.TestBed.createComponent (webpack:///Users/chad/Developer/ng2demo/~/@angular/core/bundles/core-testing.umd.js:714:0 <- src/test.ts:6718:33)
	    at Object.<anonymous> (webpack:///Users/chad/Developer/ng2demo/src/app/edit/edit.component.spec.ts:32:28 <- src/test.ts:43762:41)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:232:0 <- src/test.ts:59455:26)
	    at ProxyZoneSpec.onInvoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/proxy.js:79:0 <- src/test.ts:34825:39)
	    at ZoneDelegate.invoke (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:231:0 <- src/test.ts:59454:32)
	    at Zone.run (webpack:///Users/chad/Developer/ng2demo/~/zone.js/dist/zone.js:114:0 <- src/test.ts:59337:43)```

**Comment by gh0st** [comment]
Note, I've been following the code on the `README.md`

**Comment by mraible** [comment]
You might try looking at [edit.component.spec.ts](https://github.com/mraible/ng2-demo/blob/master/src/app/edit/edit.component.spec.ts) and comparing it to your code.

**Comment by gh0st** [comment]
Copied and pasted code from github to my project. It all looked identical except for some whitespace. Don't know what it was.
